app_estudiantes/config/routes.rb
Rails.application.routes.draw do
  resources :estudiantes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "estudiantes#index"
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app_estudiantes/app/models/estudiante.rb
class Estudiante < ApplicationRecord
    validates :nombres, :apellidos, :carrera, :carnet, :edad, :celular, presence: true
    validates :celular, format: { with: /\A[0-9]+\z/, message: "solo puede contener números" }
end

app_estudiantes/app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  before_action :set_estudiante, only: %i[ show edit update destroy ]

  # GET /estudiantes or /estudiantes.json
  def index
    @estudiantes = Estudiante.all
  end

  # GET /estudiantes/1 or /estudiantes/1.json
  def show
  end

  # GET /estudiantes/new
  def new
    @estudiante = Estudiante.new
  end

  # GET /estudiantes/1/edit
  def edit
  end

  # POST /estudiantes or /estudiantes.json
  def create
    @estudiante = Estudiante.new(estudiante_params)

    respond_to do |format|
      if @estudiante.save
        format.html { redirect_to @estudiante, notice: "Estudiante was successfully created." }
        format.json { render :show, status: :created, location: @estudiante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudiantes/1 or /estudiantes/1.json
  def update
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html { redirect_to @estudiante, notice: "Estudiante was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @estudiante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudiantes/1 or /estudiantes/1.json
  def destroy
    @estudiante.destroy!

    respond_to do |format|
      format.html { redirect_to estudiantes_path, notice: "Estudiante was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudiante
      @estudiante = Estudiante.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def estudiante_params
      params.expect(estudiante: [ :nombres, :apellidos, :carrera, :carnet, :fecha_nacimiento, :edad, :celular ])
    end
end

app_estudiantes/app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app_estudiantes/app/views/estudiantes/_estudiante.html.erb
<div id="<%= dom_id estudiante %>">
  <p>
    <strong>Nombres:</strong>
    <%= estudiante.nombres %>
  </p>

  <p>
    <strong>Apellidos:</strong>
    <%= estudiante.apellidos %>
  </p>

  <p>
    <strong>Carrera:</strong>
    <%= estudiante.carrera %>
  </p>

  <p>
    <strong>Carnet:</strong>
    <%= estudiante.carnet %>
  </p>

  <p>
    <strong>Fecha nacimiento:</strong>
    <%= estudiante.fecha_nacimiento %>
  </p>

  <p>
    <strong>Edad:</strong>
    <%= estudiante.edad %>
  </p>

  <p>
    <strong>Celular:</strong>
    <%= estudiante.celular %>
  </p>

</div>

app_estudiantes/app/views/estudiantes/_form.html.erb
<%= form_with(model: estudiante, local: true) do |f| %>
  <% if estudiante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estudiante.errors.count, "error") %> impidieron guardar el estudiante:</h2>
      <ul>
      <% estudiante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombres %>
    <%= f.text_field :nombres %>
  </div>

   <div class="field">
    <%= f.label :apellidos %>
    <%= f.text_field :apellidos %>
  </div>

   <div class="field">
    <%= f.label :carrera %>
    <%= f.text_field :carrera %>
  </div>

   <div class="field">
    <%= f.label :carnet %>
    <%= f.text_field :carnet %>
  </div>


  <div class="field">
    <%= f.label :fecha_nacimiento %>
    <%= f.date_select :fecha_nacimiento, start_year: Date.today.year - 70, end_year: Date.today.year, order: [:day, :month, :year] %>
  </div>

  <div class="field">
    <%= f.label :celular %>
    <%= f.text_field :celular, placeholder: "Solo números" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app_estudiantes/app/views/estudiantes/edit.html.erb
<% content_for :title, "Editing estudiante" %>

<h1>Editing estudiante</h1>

<%= render "form", estudiante: @estudiante %>

<br>

<div>
  <%= link_to "Show this estudiante", @estudiante %> |
  <%= link_to "Back to estudiantes", estudiantes_path %>
</div>

app_estudiantes/app/views/estudiantes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Estudiantes" %>

<h1>Estudiantes</h1>

<div id="estudiantes">
  <% @estudiantes.each do |estudiante| %>
    <%= render estudiante %>
    <p>
      <%= link_to "Show this estudiante", estudiante %>
    </p>
  <% end %>
</div>

<%= link_to "New estudiante", new_estudiante_path %>

app_estudiantes/app/views/estudiantes/new.html.erb
<% content_for :title, "New estudiante" %>

<h1>New estudiante</h1>

<%= render "form", estudiante: @estudiante %>

<br>

<div>
  <%= link_to "Back to estudiantes", estudiantes_path %>
</div>

app_estudiantes/app/views/estudiantes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @estudiante %>

<div>
  <%= link_to "Edit this estudiante", edit_estudiante_path(@estudiante) %> |
  <%= link_to "Back to estudiantes", estudiantes_path %>

  <%= button_to "Destroy this estudiante", @estudiante, method: :delete %>
</div>

app_estudiantes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "App Estudiantes" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>